#!/usr/bin/env bash
# filterscope installer — creates the ~/.local/bin/filterscope launcher.
set -e
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="${HOME}/.local/bin"
mkdir -p "$BIN"

cat > "$BIN/filterscope" <<EOF
#!/usr/bin/env bash
# filterscope launcher (generated by install.sh)
DIR="$DIR"
cmd="\${1:-tui}"
case "\$cmd" in
  tui|"")     exec python3 "\$DIR/tui.py" "\${@:2}" ;;
  scan)       exec python3 "\$DIR/filtertest.py" "\${@:2}" ;;
  compare)    exec python3 "\$DIR/compare.py" "\${@:2}" ;;
  history)    exec python3 "\$DIR/history.py" "\${@:2}" ;;
  wg|wgcheck) exec python3 "\$DIR/wgcheck.py" "\${@:2}" ;;
  warp)       exec python3 "\$DIR/warp.py" "\${@:2}" ;;
  *)          exec python3 "\$DIR/tui.py" "\$@" ;;
esac
EOF
chmod +x "$BIN/filterscope"
chmod +x "$DIR"/*.py

echo "installed: $BIN/filterscope  (source: $DIR)"
case ":$PATH:" in
  *":$BIN:"*) echo "PATH ok → type 'filterscope' to run" ;;
  *) echo "WARNING: $BIN is not on PATH. Add to ~/.bashrc:"
     echo "  export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
esac
